services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python src/main.py
    env_file:
      - ./.env
    environment:
      PYTHONPATH: /app
    depends_on:
      - database
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: abcde
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
